---
kind: pipeline
name: int-sqlite-conversation
services:
- image: ghcr.io/nextcloud/continuous-integration-redis:latest
  name: cache
steps:
- commands:
  - bash tests/drone-run-integration-tests.sh || exit 0
  - composer --version
  - composer self-update --2
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DATABASEHOST
  - cd ../server
  - cd apps/$APP_NAME
  - composer install --no-dev
  - cd ../..
  - ./occ app:enable $APP_NAME
  - git clone --depth 1 -b $NOTIFICATIONS_BRANCH https://github.com/nextcloud/notifications
    apps/notifications
  - ./occ app:enable --force notifications
  - git clone --depth 1 -b $GUESTS_BRANCH https://github.com/nextcloud/guests apps/guests
  - ./occ app:enable --force guests
  - git clone --depth 1 -b $CSB_BRANCH https://github.com/nextcloud/call_summary_bot
    apps/call_summary_bot
  - ./occ app:enable --force call_summary_bot
  - cd apps/$APP_NAME/tests/integration/
  - bash run.sh features/conversation
  environment:
    APP_NAME: spreed
    CORE_BRANCH: stable27
    CSB_BRANCH: main
    DATABASEHOST: sqlite
    GUESTS_BRANCH: master
    NOTIFICATIONS_BRANCH: stable27
  image: ghcr.io/nextcloud/continuous-integration-php8.2:latest
  name: integration-conversation
trigger:
  branch:
  - master
  - stable*
  event:
  - pull_request
  - push
---
kind: pipeline
name: int-mysql-conversation
services:
- image: ghcr.io/nextcloud/continuous-integration-redis:latest
  name: cache
- command:
  - --innodb_large_prefix=true
  - --innodb_file_format=barracuda
  - --innodb_file_per_table=true
  - --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
  environment:
    MYSQL_DATABASE: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
  image: ghcr.io/nextcloud/continuous-integration-mariadb-10.4:10.4
  name: mysql
  tmpfs:
  - /var/lib/mysql
steps:
- commands:
  - bash tests/drone-run-integration-tests.sh || exit 0
  - composer --version
  - composer self-update --2
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DATABASEHOST
  - cd ../server
  - cd apps/$APP_NAME
  - composer install --no-dev
  - cd ../..
  - ./occ app:enable $APP_NAME
  - git clone --depth 1 -b $NOTIFICATIONS_BRANCH https://github.com/nextcloud/notifications
    apps/notifications
  - ./occ app:enable --force notifications
  - git clone --depth 1 -b $GUESTS_BRANCH https://github.com/nextcloud/guests apps/guests
  - ./occ app:enable --force guests
  - git clone --depth 1 -b $CSB_BRANCH https://github.com/nextcloud/call_summary_bot
    apps/call_summary_bot
  - ./occ app:enable --force call_summary_bot
  - cd apps/$APP_NAME/tests/integration/
  - bash run.sh features/conversation
  environment:
    APP_NAME: spreed
    CORE_BRANCH: stable27
    CSB_BRANCH: main
    DATABASEHOST: mysql
    GUESTS_BRANCH: master
    NOTIFICATIONS_BRANCH: stable27
  image: ghcr.io/nextcloud/continuous-integration-php8.2:latest
  name: integration-conversation
trigger:
  branch:
  - master
  - stable*
  event:
  - pull_request
  - push
---
kind: pipeline
name: int-pgsql-conversation
services:
- image: ghcr.io/nextcloud/continuous-integration-redis:latest
  name: cache
- environment:
    POSTGRES_DB: oc_autotest
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_PASSWORD: owncloud
    POSTGRES_USER: oc_autotest
  image: ghcr.io/nextcloud/continuous-integration-postgres-13:postgres-13
  name: pgsql
  tmpfs:
  - /var/lib/postgresql/data
steps:
- commands:
  - bash tests/drone-run-integration-tests.sh || exit 0
  - composer --version
  - composer self-update --2
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DATABASEHOST
  - cd ../server
  - cd apps/$APP_NAME
  - composer install --no-dev
  - cd ../..
  - ./occ app:enable $APP_NAME
  - git clone --depth 1 -b $NOTIFICATIONS_BRANCH https://github.com/nextcloud/notifications
    apps/notifications
  - ./occ app:enable --force notifications
  - git clone --depth 1 -b $GUESTS_BRANCH https://github.com/nextcloud/guests apps/guests
  - ./occ app:enable --force guests
  - git clone --depth 1 -b $CSB_BRANCH https://github.com/nextcloud/call_summary_bot
    apps/call_summary_bot
  - ./occ app:enable --force call_summary_bot
  - cd apps/$APP_NAME/tests/integration/
  - bash run.sh features/conversation
  environment:
    APP_NAME: spreed
    CORE_BRANCH: stable27
    CSB_BRANCH: main
    DATABASEHOST: pgsql
    GUESTS_BRANCH: master
    NOTIFICATIONS_BRANCH: stable27
  image: ghcr.io/nextcloud/continuous-integration-php8.2:latest
  name: integration-conversation
trigger:
  branch:
  - master
  - stable*
  event:
  - pull_request
  - push
---
hmac: f8e16bd1635ba08a3d0f0d1e7c6f42b540da359ab066ee4107816e73c25e0d1f
kind: signature
